"""add_must_change_password_to_users

Revision ID: 39709df09d3e
Revises: 777040fe5c51
Create Date: 2026-03-24 19:59:56.556622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39709df09d3e'
down_revision: Union[str, None] = '777040fe5c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable with server_default=false so existing rows get FALSE
    op.add_column('users', sa.Column(
        'must_change_password', sa.Boolean(),
        nullable=True, server_default=sa.false()
    ))
    # Backfill any remaining NULLs (shouldn't be any, but be safe)
    op.execute("UPDATE users SET must_change_password = FALSE WHERE must_change_password IS NULL")
    # Now enforce NOT NULL
    op.alter_column('users', 'must_change_password', nullable=False, server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
