"""add_payment_methods

Revision ID: 59d4b9c9a4ad
Revises: e2f3a4b5c6d7
Create Date: 2026-03-24 14:59:16.369329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d4b9c9a4ad'
down_revision: Union[str, None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_payment_methods_deleted_at'), 'payment_methods', ['deleted_at'], unique=False)
    op.create_unique_constraint(None, 'branches', ['name'])
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'vehicles', ['plate'])
    op.create_unique_constraint(None, 'vendors', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'branches', type_='unique')
    op.drop_index(op.f('ix_payment_methods_deleted_at'), table_name='payment_methods')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
