"""epic17_add_payment_method_id_to_bills

Revision ID: e7c4d1ce91a8
Revises: 59d4b9c9a4ad
Create Date: 2026-03-24 16:36:26.287867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c4d1ce91a8'
down_revision: Union[str, None] = '59d4b9c9a4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bills', 'payment_methods', ['payment_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'payment_method_id')
    # ### end Alembic commands ###
